version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: server.Dockerfile
    container_name: apidesafio
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80;https://+:443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - app-network
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    container_name: angularclient
    ports:
      - "4200:80"
    depends_on:
      - api
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge