version: '3.8'

services:
  api-desafio:
     image: apidesafio:runtime
     build:
       context: .
       dockerfile: server.Dockerfile
     ports:
       - "8080:5000"
       - "8081:5001"
     environment:
       - ASPNETCORE_Kestrel__Certificates__Default__Password=awesomepass
       - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/companyemployees.pfx

  

  client-desafio:
    build:
      context: .
      dockerfile: client.Dockerfile
    container_name: angularclient
    ports:
      - "4200:80"
    depends_on:
      - api-desafio
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge